# Jupyter notebook dockers are arch specfic. 
# Uncomment the one for your architecture and comment out the other

# Base image for aarch64
FROM jupyter/scipy-notebook:aarch64-python-3.10.5

# Base image for x86_64
# FROM jupyter/scipy-notebook:latest

RUN pip3 install git+https://github.com/jpwhite4/xdmod-python.git
